version: "3.9"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - plex_config:/config
      - ${MEDIA_TV_DIR}:/tv
      - ${MEDIA_MOVIES_DIR}:/movies
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=${TRANS_USER}
      - PASS=${TRANS_PASS}
      - PEERPORT=51413
      - HOST_WHITELIST=127.0.0.1,192.168.*.*
    volumes:
      - transmission_config:/config
      - ${MEDIA_MOVIES_DIR}:/downloads
      - ${MEDIA_INCOMPLETE_DIR}:/incomplete
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - ${FILEBROWSER_PORT}:80
    volumes:
      - ${FILEBROWSER_ROOT}:/srv
      - filebrowser_config:/config
    restart: unless-stopped

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    ports:
      - ${HEIMDALL_PORT}:80
    volumes:
      - heimdall_config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped

volumes:
  plex_config:
  transmission_config:
  filebrowser_config:
  heimdall_config:
