services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
      - VERSION=docker
    volumes:
      - plex_config:/config
      - /mnt/unitek/storage/Tv:/tv
      - /mnt/unitek/storage/Movies:/movies
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - 8081:80
    restart: unless-stopped
    volumes:
      - /mnt/unitek:/srv
      - filebrowser_config:/config

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    ports:
      - "82:80"
    volumes:
      - heimdall_config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    restart: unless-stopped

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_POSTGRES_HOST: 'db'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_USER: ${POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRES_NAME: ${POSTGRES_DB}
      DISABLE_IPV6: 'true'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - npm_postgres:/var/lib/postgresql/data

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - overseerr_config:/config
    ports:
      - 5055:5055
    restart: unless-stopped

volumes:
  plex_config:
  filebrowser_config:
  heimdall_config:
  npm_data:
  npm_letsencrypt:
  npm_postgres:
  overseerr_config:
